export const LOAD_MAIN_START = 'LOAD_MAIN_START'
export const LOAD_MAIN_SUCCESS = 'LOAD_MAIN_SUCCESS'
export const LOAD_MAIN_FAILURE = 'LOAD_MAIN_FAILURE'

export const SINGIN_START = 'SINGIN_START'
export const SINGIN_SUCCESS = 'SINGIN_SUCCESS'
export const SINGIN_FAILURE = 'SINGIN_FAILURE'

export const SINGUP_START = 'SINGUP_START'
export const SINGUP_SUCCESS = 'SINGUP_SUCCESS'
export const SINGUP_FAILURE = 'SINGUP_FAILURE'