export const LOAD_MAIN_START = 'LOAD_MAIN_START'
export const LOAD_MAIN_SUCCESS = 'LOAD_MAIN_SUCCESS'
export const LOAD_MAIN_FAILURE = 'LOAD_MAIN_FAILURE'

export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const SINGUP_START = 'SINGUP_START'
export const SINGUP_SUCCESS = 'SINGUP_SUCCESS'
export const SINGUP_FAILURE = 'SINGUP_FAILURE'

export const LOGOUT_START = 'LOGOUT_START'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const SHORTCUT1_ADD = 'SHORTCUT1_ADD'
export const SHORTCUT2_ADD = 'SHORTCUT2_ADD'
export const SHORTCUT3_ADD = 'SHORTCUT3_ADD'
export const SHORTCUT4_ADD = 'SHORTCUT4_ADD'
export const SHORTCUT_UPDATE = 'SHORTCUT_UPDATE'

export const FEATCH_BINGO_ROOM_START = 'FEATCH_BINGO_ROOM_START'
export const FEATCH_BINGO_ROOM_SUCCESS = 'FEATCH_BINGO_ROOM_SUCCESS'
export const FEATCH_BINGO_ROOM_FAILURE = 'FEATCH_BINGO_ROOM_FAILURE'

export const CREATE_BINGO_ROOM_START = 'CREATE_BINGO_ROOM_START'
export const CREATE_BINGO_ROOM_SUCCESS = 'CREATE_BINGO_ROOM_SUCCESS'
export const CREATE_BINGO_ROOM_FAILURE = 'CREATE_BINGO_ROOM_FAILURE'

export const EDIT_BINGO_ROOM_START = 'EDIT_BINGO_ROOM_START'
export const EDIT_BINGO_ROOM_SUCCESS = 'EDIT_BINGO_ROOM_SUCCESS'
export const EDIT_BINGO_ROOM_FAILURE = 'EDIT_BINGO_ROOM_FAILURE'

export const DELETE_BINGO_ROOM_START = 'DELETE_BINGO_ROOM_START'
export const DELETE_BINGO_ROOM_SUCCESS = 'DELETE_BINGO_ROOM_SUCCESS'
export const DELETE_BINGO_ROOM_FAILURE = 'DELETE_BINGO_ROOM_FAILURE'